export const FETCH_UNIVARSITIES = "FETCH_UNIVARSITIES";
export const ADD_AUTHENTICATE_STATUS = "ADD_AUTHENTICATE_STATUS";
export const ADD_TASK = "ADD_TASK";
export const FETCH_POST = "FETCH_POST";
export const FETCH_DICTIONARY = "FETCH_DICTIONARY";